### ISSUE TITLE
Cannot execute test

### ISSUE THREAD

**Issue by vicpinm** [tmurakami/dexopener#14]
Hi, when I execute my test, I get: 

    Running tests

    $ adb shell am instrument -w -r   -e debug false 
    example.org.test/com.github.tmurakami.dexopener.DexOpenerAndroidJUnitRunner
    Client not ready yet..
    Started running tests
    Test running failed: Instrumentation run failed due to 'Process crashed.'
    Empty test suite.

I have configured my build.gradle as readme says.

**Comment by tmurakami** [comment]
Is there any error message in logcat?

**Comment by vicpinm** [comment]
Yes, I have this exception:

    java.lang.RuntimeException: Unable to instantiate instrumentation ComponentInfo{events.symposium.app.org.test/com.github.tmurakami.dexopener.DexOpenerAndroidJUnitRunner}: java.lang.ClassNotFoundException: Didn't find class "com.github.tmurakami.dexopener.DexOpenerAndroidJUnitRunner" on path: DexPathList[[],nativeLibraryDirectories=[/system/lib64, /system/vendor/lib64]]
                                                                              at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5973)
                                                                              at android.app.ActivityThread.-wrap1(Unknown Source:0)
                                                                              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1756)
                                                                              at android.os.Handler.dispatchMessage(Handler.java:105)
                                                                              at android.os.Looper.loop(Looper.java:164)
                                                                              at android.app.ActivityThread.main(ActivityThread.java:6809)
                                                                              at java.lang.reflect.Method.invoke(Native Method)
                                                                              at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
                                                                           Caused by: java.lang.ClassNotFoundException: Didn't find class "com.github.tmurakami.dexopener.DexOpenerAndroidJUnitRunner" on path: DexPathList[[],nativeLibraryDirectories=[/system/lib64, /system/vendor/lib64]]
                                                                              at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:93)
                                                                              at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
                                                                              at java.lang.ClassLoader.loadClass(ClassLoader.java:312)

**Comment by tmurakami** [comment]
It seems that DexOpener is not incorporated in your test application.

Does the same error occur when running `./gradlew connectedAndroidTest`?
And could you share your build.gradle?

**Comment by vicpinm** [comment]
You are right. I have restarted Android studio, and performed a clean build. Now it's working, thanks!
