### ISSUE TITLE
Instrumented test crashes using version 1.0.4 in Android Studio 3.1.2

### ISSUE THREAD

**Issue by paolop** [tmurakami/dexopener#22]
java.io.IOError: java.io.IOException: Cannot create /data/user/0/com.mypackage.debug/code_cache/dexopener
        at com.github.tmurakami.dexopener.repackaged.com.github.tmurakami.classinjector.InjectorClassLoader.injectClass(InjectorClassLoader.java:58)
        at com.github.tmurakami.dexopener.repackaged.com.github.tmurakami.classinjector.InjectorClassLoader.findClass(InjectorClassLoader.java:42)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:367)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at android.app.ActivityThread.installProvider(ActivityThread.java:6227)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:5805)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5722)
        at android.app.ActivityThread.-wrap1(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1656)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
     Caused by: java.io.IOException: Cannot create /data/user/0/com.mypackage.debug/code_cache/dexopener
        at com.github.tmurakami.dexopener.DexFileGenerator.generateDexFile(DexFileGenerator.java:39)
        at com.github.tmurakami.dexopener.AndroidClassSource$DexFileTask.call(AndroidClassSource.java:171)
        at com.github.tmurakami.dexopener.AndroidClassSource$DexFileTask.call(AndroidClassSource.java:142)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)

**Comment by tmurakami** [comment]
Thank you for reporting.
