### ISSUE TITLE
OutOfMemoryError when spinning up Instrumentation Tests

### ISSUE THREAD

**Issue by jordanmcgowan** [tmurakami/dexopener#25]
After creating my own Runner: 
```
package com.target.location

import android.app.Application
import android.content.Context
import androidx.test.runner.AndroidJUnitRunner
import com.github.tmurakami.dexopener.DexOpener

class NewJUnitRunner : AndroidJUnitRunner() {
  @Throws(ClassNotFoundException::class, IllegalAccessException::class, InstantiationException::class)
  override fun newApplication(cl: ClassLoader, className: String, context: Context): Application {
    DexOpener.install(this) // Call me first!
    return super.newApplication(cl, className, context)
  }
}
```

I am seeing this exception when starting up the tests: 
```
java.lang.OutOfMemoryError: Failed to allocate a 702649760 byte allocation with 6275072 free bytes and 341MB until OOM, max allowed footprint 50520112, growth limit 402653184
at com.github.tmurakami.dexopener.repackaged.org.ow2.asmdex.lowLevelUtils.DexFileReader.getAnnotationItemOffsetsFromAnnotationSetItem(DexFileReader.java:203)
at com.github.tmurakami.dexopener.repackaged.org.ow2.asmdex.ApplicationReader.readAndVisitAnnotations(ApplicationReader.java:1235)
at com.github.tmurakami.dexopener.repackaged.org.ow2.asmdex.ApplicationReader.visitMethods(ApplicationReader.java:777)
at com.github.tmurakami.dexopener.repackaged.org.ow2.asmdex.ApplicationReader.visitClass(ApplicationReader.java:614)
at com.github.tmurakami.dexopener.repackaged.org.ow2.asmdex.ApplicationReader.accept(ApplicationReader.java:447)
at com.github.tmurakami.dexopener.repackaged.org.ow2.asmdex.ApplicationReader.accept(ApplicationReader.java:328)
at com.github.tmurakami.dexopener.DexClassSource.getClassFile(DexClassSource.java:47)
at com.github.tmurakami.classinjector.ClassSources.getClassFile(ClassSources.java:44)
at com.github.tmurakami.dexopener.AndroidClassSource.getClassFile(AndroidClassSource.java:37)
at com.github.tmurakami.classinjector.StealthClassLoader.findClass(StealthClassLoader.java:32)
at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
at java.lang.ClassLoader.loadClass(ClassLoader.java:367)
at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
at dalvik.system.DexFile.defineClassNative(Native Method)
at dalvik.system.DexFile.defineClass(DexFile.java:282)
at dalvik.system.DexFile.loadClassBinaryName(DexFile.java:275)
at dalvik.system.DexFile.loadClass(DexFile.java:264)
at com.github.tmurakami.classinjector.android.DexClassFile.toClass(DexClassFile.java:43)
at com.github.tmurakami.classinjector.StealthClassLoader.findClass(StealthClassLoader.java:40)
at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
at java.lang.ClassLoader.loadClass(ClassLoader.java:367)
at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
at java.lang.reflect.Executable.getMethodReturnTypeInternal(Native Method)
at java.lang.reflect.Method.getReturnType(Method.java:141)
at java.lang.Class.getDeclaredMethods(Class.java:1880)
at org.junit.internal.MethodSorter.getDeclaredMethods(MethodSorter.java:54)
at org.junit.runners.model.TestClass.scanAnnotatedMembers(TestClass.java:65)
at org.junit.runners.model.TestClass.<init>(TestClass.java:57)
at org.junit.runners.ParentRunner.createTestClass(ParentRunner.java:88)
at org.junit.runners.ParentRunner.<init>(ParentRunner.java:83)
at org.junit.runners.BlockJUnit4ClassRunner.<init>(BlockJUnit4ClassRunner.java:65)
at androidx.test.internal.runner.junit4.AndroidJUnit4ClassRunner.<init>(AndroidJUnit4ClassRunner.java:43)
at androidx.test.runner.AndroidJUnit4.<init>(AndroidJUnit4.java:52)
at java.lang.reflect.Constructor.newInstance0(Native Method)
at java.lang.reflect.Constructor.newInstance(Constructor.java:334)
at androidx.test.internal.runner.junit4.AndroidAnnotatedBuilder.buildAndroidRunner(AndroidAnnotatedBuilder.java:71)
at androidx.test.internal.runner.junit4.AndroidAnnotatedBuilder.runnerForClass(AndroidAnnotatedBuilder.java:48)
at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:26)
at androidx.test.internal.runner.AndroidRunnerBuilder.runnerForClass(AndroidRunnerBuilder.java:153)
at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
at androidx.test.internal.runner.TestLoader.doCreateRunner(TestLoader.java:73)
at androidx.test.internal.runner.TestLoader.getRunnersFor(TestLoader.java:104)
at androidx.test.internal.runner.TestRequestBuilder.build(TestRequestBuilder.java:789)
at androidx.test.runner.AndroidJUnitRunner.buildRequest(AndroidJUnitRunner.java:543)
at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:386)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2074)```

The test is pretty straight forward and is just using one `mock()` so I'm not sure off the top of my head what could be causing this. Perhaps it's even a machine specific issue?

**Comment by tmurakami** [comment]
Please use the latest version of DexOpener.

**Comment by jordanmcgowan** [comment]
This has resolved my issue, thank you for the quick response!
