### ISSUE TITLE
Using a Spy on TestApplication

### ISSUE THREAD

**Issue by maxtower** [tmurakami/dexopener#26]
Running this code:
```
DexOpener.install(this)
    return Mockito.spy(super.newApplication(cl, "com.xyz.test.TestApp", context))
```

gives me this error
```
org.mockito.exceptions.base.MockitoException: 
    Mockito cannot mock this class: class com.xyz.test.TestApp
```

Do you know any way I can place a spy on my custom Application class so that I can mock some methods on it?

My setup is working when I remove the spy.

**Comment by tmurakami** [comment]
Could you show me the stacktrace?

**Comment by maxtower** [comment]
https://github.com/maxtower/dexopener/tree/mockito-spy-test-app
Made a test case for you here based on your simple example.
```
 MyActivity.this.getDir("target", Context.MODE_PRIVATE)
    or
    getInstrumentation().getTargetContext().getCacheDir().getPath()
        at com.example.dexopener.simple.MyAndroidJUnitRunner.newApplication(MyAndroidJUnitRunner.java:34)
        at android.app.LoadedApk.makeApplication(LoadedApk.java:983)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5715)
        at android.app.ActivityThread.-wrap1(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1656)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
     Caused by: org.mockito.exceptions.base.MockitoException: 
    Could not look up implicit location for storing generated classes
    
    You can configure an explicit location by setting the system property
    'org.mockito.android.target' to a folder for storing generated class files
    This location must be in private scope for most API versions, for example:
    
    MyActivity.this.getDir("target", Context.MODE_PRIVATE)
    or
    getInstrumentation().getTargetContext().getCacheDir().getPath()
        at net.bytebuddy.TypeCache.findOrInsert(TypeCache.java:152)
        at net.bytebuddy.TypeCache$WithInlineExpunction.findOrInsert(TypeCache.java:365)
        at net.bytebuddy.TypeCache.findOrInsert(TypeCache.java:174)
        at net.bytebuddy.TypeCache$WithInlineExpunction.findOrInsert(TypeCache.java:376)
        	... 11 more
```

**Comment by tmurakami** [comment]
This is not a DexOpener issue.

As shown in your stacktrace, specify the `org.mockito.android.target` system property before calling `Mockito.spy()`.

```java
System.setProperty("org.mockito.android.target", context.getCacheDir().getPath());
```
