### ISSUE TITLE
RuntimeException occurs when minSdkVersion is 26

### ISSUE THREAD

**Issue by tmurakami** [tmurakami/dexopener#4]
Smali does not support Dex format version 038.

Logcat is here:

```
06-09 20:35:12.769  4389  4389 E AndroidRuntime: FATAL EXCEPTION: main
06-09 20:35:12.769  4389  4389 E AndroidRuntime: Process: com.example.myapplication, PID: 4389
06-09 20:35:12.769  4389  4389 E AndroidRuntime: java.lang.RuntimeException: Unable to create application com.example.myapplication.test.TestApp: com.github.tmurakami.dexopener.repackaged.org.jf.dexlib2.util.DexUtil$UnsupportedFile: Dex version 038 is not supported
06-09 20:35:12.769  4389  4389 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5793)
06-09 20:35:12.769  4389  4389 E AndroidRuntime: 	at android.app.ActivityThread.-wrap1(Unknown Source:0)
06-09 20:35:12.769  4389  4389 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1661)
06-09 20:35:12.769  4389  4389 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:105)
06-09 20:35:12.769  4389  4389 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)
06-09 20:35:12.769  4389  4389 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6540)
06-09 20:35:12.769  4389  4389 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
06-09 20:35:12.769  4389  4389 E AndroidRuntime: 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
06-09 20:35:12.769  4389  4389 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
06-09 20:35:12.769  4389  4389 E AndroidRuntime: Caused by: com.github.tmurakami.dexopener.repackaged.org.jf.dexlib2.util.DexUtil$UnsupportedFile: Dex version 038 is not supported
06-09 20:35:12.769  4389  4389 E AndroidRuntime: 	at com.github.tmurakami.dexopener.repackaged.org.jf.dexlib2.util.DexUtil.verifyDexHeader(SourceFile:94)
06-09 20:35:12.769  4389  4389 E AndroidRuntime: 	at com.github.tmurakami.dexopener.repackaged.org.jf.dexlib2.dexbacked.DexBackedDexFile.<init>(SourceFile:78)
06-09 20:35:12.769  4389  4389 E AndroidRuntime: 	at com.github.tmurakami.dexopener.repackaged.org.jf.dexlib2.dexbacked.DexBackedDexFile.<init>(SourceFile:104)
06-09 20:35:12.769  4389  4389 E AndroidRuntime: 	at com.github.tmurakami.dexopener.DexFilesFactory.newDexFiles(DexFilesFactory.java:39)
06-09 20:35:12.769  4389  4389 E AndroidRuntime: 	at com.github.tmurakami.dexopener.AndroidClassSource.newDelegate(AndroidClassSource.java:64)
06-09 20:35:12.769  4389  4389 E AndroidRuntime: 	at com.github.tmurakami.dexopener.AndroidClassSource.getDelegate(AndroidClassSource.java:44)
06-09 20:35:12.769  4389  4389 E AndroidRuntime: 	at com.github.tmurakami.dexopener.AndroidClassSource.getClassFile(AndroidClassSource.java:38)
06-09 20:35:12.769  4389  4389 E AndroidRuntime: 	at com.github.tmurakami.dexopener.repackaged.com.github.tmurakami.classinjector.StealthClassLoader.findClass(SourceFile:32)
06-09 20:35:12.769  4389  4389 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
06-09 20:35:12.769  4389  4389 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:367)
06-09 20:35:12.769  4389  4389 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
06-09 20:35:12.769  4389  4389 E AndroidRuntime: 	at com.example.myapplication.test.TestApp.onCreate(TestApp.kt:11)
06-09 20:35:12.769  4389  4389 E AndroidRuntime: 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1118)
06-09 20:35:12.769  4389  4389 E AndroidRuntime: 	at android.support.test.runner.MonitoringInstrumentation.callApplicationOnCreate(MonitoringInstrumentation.java:323)
06-09 20:35:12.769  4389  4389 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5790)
06-09 20:35:12.769  4389  4389 E AndroidRuntime: 	... 8 more
```

**Comment by tmurakami** [comment]
This issue has been fixed in version 0.10.1.
